# Generated by Django 4.2.17 on 2024-12-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='mail',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='member',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='pagoOk',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='tel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
