# Generated by Django 4.2.17 on 2024-12-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_socio_mail_socio_member_socio_nombre_socio_pagook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='pagoOk',
            field=models.BooleanField(default=True),
        ),
    ]
