# Generated by Django 4.2.17 on 2024-12-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_socio_pagook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actividad',
        ),
        migrations.DeleteModel(
            name='socio',
        ),
    ]
